// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UritusedData;

namespace UritusedData.Migrations
{
    [DbContext(typeof(UritusedContext))]
    [Migration("20220410104351_update2")]
    partial class update2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UritusedData.Models.Osalejad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Eesnimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Isikukood")
                        .HasColumnType("real");

                    b.Property<string>("Lisainfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Makseviis")
                        .HasColumnType("int");

                    b.Property<string>("Perenimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UritusedId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UritusedId");

                    b.ToTable("Osalejad");
                });

            modelBuilder.Entity("UritusedData.Models.Uritused", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Koht")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lisainfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Toimumisaeg")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uritusenimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uritused");
                });

            modelBuilder.Entity("UritusedData.Models.Osalejad", b =>
                {
                    b.HasOne("UritusedData.Models.Uritused", null)
                        .WithMany("Osalejad")
                        .HasForeignKey("UritusedId");
                });
#pragma warning restore 612, 618
        }
    }
}
